- config.yaml
- markdown/org/exam.md
> [VL]: Exams

- markdown/org/teaser.md
> [VL]: Teaser (Modulvorstellung)

- markdown/semantics/symboltables/antlr.md
Adds placeholder for new dedicated ANTLR session.
> [VL] New ANTLR Session

- markdown/parsing/antlr.md
@malt-r der ist irgendwie durchgerutscht, oder?
> [VL] Parsing ANTLR: add previous material

- markdown/interpretation/gc.md
- markdown/lexing/antlr.md
- markdown/parsing/antlr.md
- markdown/parsing/cfg.md
- markdown/parsing/finalwords.md
- markdown/parsing/ll-parser-impl.md
- markdown/parsing/ll-parser-theory.md
- markdown/parsing/recovery.md
- markdown/semantics/symboltables/antlr.md
Nach dem Entfernen von bisherigen Sitzungen und dem Einfügen neuer Inhalte müssen die Gewichte für Hugo angepasst werden. Leider muss das innerhalb des Inhalts erfolgen, obwohl das eine Art Konfiguration ist. Ja, ich schaue in deine Richtung, Hugo!
> [VL] fix weights

- markdown/interpretation/astdriven-part1.md
- markdown/interpretation/astdriven-part2.md
- markdown/interpretation/gc.md
- markdown/intro/languages.md
- markdown/intro/overview.md
- markdown/org/teaser.md
- markdown/parsing/ll-parser-impl.md
- markdown/parsing/recovery.md
- markdown/semantics/symboltables/classes.md
- markdown/semantics/symboltables/functions.md
- markdown/semantics/symboltables/scopes.md
> [ORG] Zitate und Fremdmaterial prüfen: TULLU-Regel

- .github/actions/alpine-pandoc-hugo/Dockerfile
- .github/actions/alpine-pandoc-hugo/install-packages.sh
> [TOOLING] Update Docker

- markdown/assignments/_index.md
- markdown/assignments/sheet01.md
- markdown/assignments/sheet02.md
- markdown/assignments/sheet03.md
- markdown/assignments/sheet04.md
- markdown/assignments/sheet05.md
- markdown/credits.md
- markdown/imprint.md
- markdown/intermediate/_index.md
- markdown/interpretation/_index.md
- markdown/intro/_index.md
- markdown/lexing/_index.md
- markdown/org/_index.md
- markdown/org/exam.md
- markdown/org/grading.md
- markdown/org/resources.md
- markdown/org/schedule.md
- markdown/org/syllabus.md
- markdown/org/teaser.md
- markdown/parsing/_index.md
- markdown/privacy.md
- markdown/semantics/_index.md
- markdown/semantics/symboltables/_index.md
> [VL] Fix landing pages

- README.md
Fixes #25
reicht erstmal, mehr kommt später bei der überarbeitung und nutzung des readme.md als startseite ...
> [README] fix formatting

- config.yaml
> Open ILIAS Course 

- data/ba/schedule.yaml
- markdown/_index.ba.md
- markdown/assignments/sheet04.ba.md
- markdown/org/grading.ba.md
- Raum: C1 
- Abgabefrist: Mi, 08:00 Uhr
- Deadlines für die Übungsblätter
- Fix typos
fixes #61
> [ORGA] Bachelor: Finalise deadlines, rooms, schedule ... 

- data/ma/schedule.yaml
- markdown/_index.ma.md
- markdown/org/grading.ma.md
- Raum: C1 
- Abgabefrist: Di, 14:00 Uhr
- Deadlines für die Übungsblätter
- Fix typos
fixes #61
> [ORGA] Master: Finalise deadlines, rooms, schedule ... 

- markdown/org/grading.ma.md
Behebe Copy&Paste-Fehler bei den Vortragsthemen im Master
fixes #82
> [ORGA] fix grading ma

- markdown/org/faq.ba.md
Basierend auf den häufigsten Fragen in der Vorstellungsrunde im Master habe ich eine vorläufige FAQ für den Bachelor erstellt.
> [FAQ] add initial FAQ (bachelor)

- markdown/org/faq.ma.md
Aus den häufigsten Fragen in der Vorstellungsrunde im Master habe ich eine vorläufige FAQ erstellt.
> [FAQ] add initial FAQ (master)

- markdown/_index.ba.md
- markdown/_index.ma.md
- markdown/org/faq.ba.md
- markdown/org/faq.ma.md
Klarstellung: 
- Flipped Classroom: Sprechstunde ist online
- Vorlesung BC ist vor Ort mit der Möglichkeit, ggf. per Zoom teilzunehmen
> [ORGA] Fix VL-Modus

- markdown/frontend/lexing/antlr.ba.md
- markdown/frontend/lexing/antlr.ma.md
- markdown/frontend/lexing/src/Demo.g4
- markdown/frontend/lexing/src/Hello.g4
- markdown/frontend/lexing/src/Longest.g4
- markdown/frontend/lexing/src/Main.java
- markdown/frontend/lexing/src/Nongreedy.g4
- markdown/frontend/lexing/src/Order.g4
- markdown/frontend/lexing/src/env.sh
Neue Einheiten: Lexing mit ANTLR (BA, MA).
> [VL] Add ANTLR Lexer

- markdown/frontend/parsing/cfg.ba.md
- markdown/frontend/parsing/cfg.ma.md
> [VL] Rework Lecture CFG (MA)

- README.md
- markdown/_index.ba.md
- markdown/_index.ma.md
> [ORG] add url to 'We CAN virtuOWL' project

- markdown/backend/interpretation/astdriven-part1.ba.md
- markdown/backend/interpretation/astdriven-part1.ma.md
- markdown/backend/interpretation/astdriven-part2.ba.md
- markdown/backend/interpretation/astdriven-part2.ma.md
- markdown/backend/interpretation/syntaxdriven.ba.md
- markdown/backend/interpretation/syntaxdriven.ma.md
- Interpreter (Bachelor): Blatt 03
- Interpreter (Master): Kein Blatt
> [VL] Interpreter and Assignments

- markdown/assignments/sheet01.ba.md
- markdown/assignments/sheet01.ma.md
> [ASSIGNMENT] Blatt 01: add 'self' as first parameter to methods

- markdown/frontend/semantics/symboltables/scopes.ba.md
- markdown/frontend/semantics/symboltables/scopes.ma.md
remove superfluous/erroneous spaces
> [VL] Scopes: Fix link to YT video

- markdown/backend/optimization.ma.md
> [VL] Optimization (MA)

- data/ba/schedule.yaml
Spiegelt die lokalen Anpassungen im Zeitplan für das WS22 wider - **NICHT MERGEN**.
> [W22] Verschiebe VL von KW48 auf KW49

- .github/workflows/hugo.yaml
- .github/workflows/slides.yaml
> [Tool] remove tex/dot conversion from workflows

- lecture/backend/interpretation/astdriven-part1.md
- lecture/backend/interpretation/syntaxdriven.md
- lecture/intro/overview.md
> VL: use raw-links into github repo for images/markdown files in yaml (tldr, challenges)

- readme.md
> org: add planning for the oral exams

- lecture/backend/interpretation/astdriven-part1.md
- lecture/backend/interpretation/astdriven-part2.md
- lecture/backend/minipython-builder.md
- lecture/frontend/lexing/regular.md
- lecture/frontend/semantics/attribgrammars.md
- lecture/frontend/semantics/symboltables/intro-symbtab.md
- lecture/intro/languages.md
- lecture/readme.md
to prepare for relearn 5.24.x and hugo 0.123
> Hugo: replace 'menuTitle' w/ 'linkTitle'

- lecture/02-parsing/cfg.md
- lecture/02-parsing/ll-parser.md
> Lecture: reduce LL parser session

- lecture/02-parsing/cfg.md
- lecture/02-parsing/ll-parser.md
> Lecture: rework CFG and add LL slides

- homework/sheet03.md
> Homework: rework B03 (ANTLR) 

- homework/sheet04.md
- homework/sheet04x.md
- homework/src/sample_project/src/main/antlr/MiniC.g4
- readme.md
> Homework: rework B04 (Symboltabelle) 

- homework/sheet05.md
- homework/sheet05x.md
- homework/src/sample_project/src/main/antlr/MiniLisp.g4
- readme.md
> Homework: rework B05 (Interpreter) 

- homework/sheet02.md
- lecture/02-parsing/cfg.md
> Homework: rework B02 (CFG)

- homework/sheet04x.md
- homework/sheet07.md
- homework/sheet07x.md
> Homework: rework B07 (Mini-Project)
